# Start Generation Here
[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "functions"

[redirects]
  /*    /index.html   200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
