# Simple workflow for deploying static content to Netlify
name: Deploy static content to Netlify

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the NETLIFY_TOKEN permissions to allow deployment to Netlify
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'netlify'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: netlify
      url: ${{ steps.deployment.outputs.site_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Netlify
        id: deployment
        uses: nwtgck/actions-netlify@v1.1.0
        with:
          publish-dir: './dist'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
